import type { Recipe } from '../types'

export const SEED_RECIPES: Recipe[] = [
  {
    id: '11111111-0000-0000-0000-000000000001',
    name: 'Poulet roti aux herbes',
    emoji: '🍗',
    photo_url: null,
    prep_time: 15,
    cook_time: 60,
    servings: 4,
    tags: ['elabore', 'dinner'],
    ingredients: [
      { name: 'poulet entier', quantity: 1.8, unit: 'kg', note: null },
      { name: 'ail', quantity: 4, unit: 'piece', note: 'gousses' },
      { name: 'romarin', quantity: 3, unit: 'botte', note: 'frais' },
      { name: 'thym', quantity: 3, unit: 'botte', note: 'frais' },
      { name: 'huile olive', quantity: 3, unit: 'cas', note: null },
      { name: 'citron', quantity: 1, unit: 'piece', note: 'zeste et jus' },
      { name: 'sel', quantity: 1, unit: 'cac', note: null },
      { name: 'poivre', quantity: 1, unit: 'pincee', note: null },
    ],
    steps: [
      'Prechauffer le four a 200C.',
      'Ecraser ail avec huile, romarin, thym, citron, sel et poivre.',
      'Glisser moitie sous la peau, badigeonner exterieur avec le reste.',
      'Enfourner 60 minutes en arrosant toutes les 20 minutes.',
      'Laisser reposer 10 minutes avant de decouper.',
    ],
    macros: { kcal: 420, p: 48, g: 2, l: 24, confidence: 'high' },
    notes: 'Parfait avec des pommes de terre roties dans le meme plat.',
    created_at: '2025-01-01T10:00:00.000Z',
    updated_at: '2025-01-01T10:00:00.000Z',
  },
  {
    id: '11111111-0000-0000-0000-000000000002',
    name: 'Bowl de riz au saumon',
    emoji: '🐟',
    photo_url: null,
    prep_time: 10,
    cook_time: 20,
    servings: 2,
    tags: ['rapide', 'lunch', 'mealprep'],
    ingredients: [
      { name: 'saumon', quantity: 300, unit: 'g', note: 'filets sans peau' },
      { name: 'riz japonais', quantity: 180, unit: 'g', note: 'cuit' },
      { name: 'edamame', quantity: 100, unit: 'g', note: 'surgeles' },
      { name: 'avocat', quantity: 1, unit: 'piece', note: 'mur' },
      { name: 'sauce soja', quantity: 2, unit: 'cas', note: null },
      { name: 'sesame', quantity: 1, unit: 'cas', note: 'graines grillees' },
      { name: 'gingembre', quantity: 1, unit: 'cac', note: 'rape' },
    ],
    steps: [
      'Cuire le riz selon les instructions du paquet.',
      'Assaisonner saumon avec sauce soja et gingembre. Cuire a la poele 3 min chaque cote.',
      'Decongeler les edamame a la poele 2 minutes.',
      'Dresser le riz, ajouter saumon emmiette, avocat tranche et edamame.',
      'Parsemer de sesame et un filet de sauce soja.',
    ],
    macros: { kcal: 580, p: 42, g: 55, l: 18, confidence: 'medium' },
    notes: 'Peut se preparer a lavance, garder les composants separes.',
    created_at: '2025-01-02T10:00:00.000Z',
    updated_at: '2025-01-02T10:00:00.000Z',
  },
  {
    id: '11111111-0000-0000-0000-000000000003',
    name: 'Pasta e fagioli',
    emoji: '🫘',
    photo_url: null,
    prep_time: 10,
    cook_time: 35,
    servings: 3,
    tags: ['elabore', 'dinner'],
    ingredients: [
      { name: 'haricots borlotti', quantity: 400, unit: 'g', note: 'en boite, egouttes' },
      { name: 'pates courtes', quantity: 200, unit: 'g', note: 'ditalini ou petites pennes' },
      { name: 'lardons fumes', quantity: 100, unit: 'g', note: null },
      { name: 'tomates concassees', quantity: 200, unit: 'g', note: 'en boite' },
      { name: 'ail', quantity: 3, unit: 'piece', note: 'gousses' },
      { name: 'romarin', quantity: 1, unit: 'botte', note: 'frais' },
      { name: 'bouillon de legumes', quantity: 500, unit: 'ml', note: null },
      { name: 'parmesan', quantity: 40, unit: 'g', note: 'rape' },
      { name: 'huile olive', quantity: 2, unit: 'cas', note: null },
    ],
    steps: [
      'Faire revenir lardons dans huile 3 minutes. Ajouter ail et romarin.',
      'Ajouter les tomates, cuire 5 minutes.',
      'Ajouter haricots et bouillon. Laisser mijoter 15 minutes.',
      'Ecraser grossierement 1/3 des haricots pour epaissir.',
      'Ajouter les pates et cuire le temps indique sur le paquet.',
      'Servir avec parmesan et un filet huile olive.',
    ],
    macros: { kcal: 510, p: 28, g: 68, l: 12, confidence: 'medium' },
    notes: 'Encore meilleur le lendemain. Ajouter de eau si trop epais.',
    created_at: '2025-01-03T10:00:00.000Z',
    updated_at: '2025-01-03T10:00:00.000Z',
  },
  {
    id: '11111111-0000-0000-0000-000000000004',
    name: 'Omelette proteинee aux champignons',
    emoji: '🍳',
    photo_url: null,
    prep_time: 5,
    cook_time: 8,
    servings: 1,
    tags: ['rapide', 'lunch'],
    ingredients: [
      { name: 'oeufs', quantity: 3, unit: 'piece', note: null },
      { name: 'blancs oeufs', quantity: 2, unit: 'piece', note: null },
      { name: 'champignons de Paris', quantity: 120, unit: 'g', note: 'emince' },
      { name: 'epinards frais', quantity: 40, unit: 'g', note: null },
      { name: 'fromage frais', quantity: 30, unit: 'g', note: null },
      { name: 'ciboulette', quantity: 1, unit: 'botte', note: 'ciselee' },
      { name: 'huile olive', quantity: 1, unit: 'cac', note: null },
    ],
    steps: [
      'Faire sauter champignons a feu vif 3 minutes. Ajouter epinards 1 minute.',
      'Battre oeufs et blancs avec sel et poivre.',
      'Verser sur legumes, cuire a feu moyen en ramenant les bords vers le centre.',
      'Deposer fromage frais au centre, plier et servir avec ciboulette.',
    ],
    macros: { kcal: 310, p: 34, g: 5, l: 17, confidence: 'high' },
    notes: null,
    created_at: '2025-01-04T10:00:00.000Z',
    updated_at: '2025-01-04T10:00:00.000Z',
  },
  {
    id: '11111111-0000-0000-0000-000000000005',
    name: 'Chili con carne',
    emoji: '🌶️',
    photo_url: null,
    prep_time: 15,
    cook_time: 50,
    servings: 4,
    tags: ['elabore', 'mealprep', 'dinner'],
    ingredients: [
      { name: 'boeuf hache', quantity: 500, unit: 'g', note: '15% MG' },
      { name: 'haricots rouges', quantity: 400, unit: 'g', note: 'en boite' },
      { name: 'tomates concassees', quantity: 400, unit: 'g', note: 'en boite' },
      { name: 'oignon', quantity: 1, unit: 'piece', note: 'emince' },
      { name: 'ail', quantity: 3, unit: 'piece', note: 'gousses' },
      { name: 'poivron rouge', quantity: 1, unit: 'piece', note: 'en des' },
      { name: 'piment chipotle', quantity: 1, unit: 'cac', note: null },
      { name: 'cumin', quantity: 2, unit: 'cac', note: null },
      { name: 'paprika fume', quantity: 1, unit: 'cac', note: null },
      { name: 'bouillon de boeuf', quantity: 200, unit: 'ml', note: null },
    ],
    steps: [
      'Faire revenir oignon et ail a feu moyen 5 minutes.',
      'Ajouter poivron et epices, cuire 2 minutes.',
      'Monter le feu, ajouter viande et faire colorer 5 minutes en remuant.',
      'Ajouter tomates, haricots et bouillon. Porter a ebullition.',
      'Reduire et laisser mijoter a couvert 40 minutes.',
    ],
    macros: { kcal: 490, p: 40, g: 35, l: 18, confidence: 'high' },
    notes: 'Se congele tres bien en portions. Servir avec du riz ou du pain.',
    created_at: '2025-01-05T10:00:00.000Z',
    updated_at: '2025-01-05T10:00:00.000Z',
  },
]
